[package]
name = "na"
version = "0.1.0"
authors = ["arturo castro <arturo@openframeworks.cc>"]

[dependencies]
nalgebra = "0.11"
alga = "0.5"
num = "0.1"
typenum = "1.4"
generic-array = "0.2"

#[dependencies.nalgebra]
#path = "../nalgebra"
